dist: xenial
sudo: required

matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: 3.6
    after_success:
    - bash scripts/bump_script.sh
    # TODO - put pypi credentials in travis repository settings
    deploy:
      provider: pypi
      user: $PYPI_USER
      password: $PYPI_PASSWORD
      on:
        tags: true
  - os: linux
    dist: xenial
    language: python
    python: 3.7
  - os: osx
    language: generic
    env: PYTHON_VERSION="3.6"
  - os: osx
    language: generic
    env: PYTHON_VERSION="3.7"

before_install:
# getting around how travis sets boto configuration
# see https://github.com/travis-ci/travis-ci/issues/7940
- export BOTO_CONFIG=/dev/null
- pip install --upgrade bump2version
# TODO - add github personal access token in repository settings
- bash scripts/setup_git.sh

install:
- cd $TRAVIS_BUILD_DIR && bash scripts/travis_install.sh

script:
- python -m pytest

branches:
  only:
  - master
